# Generated by Django 2.0.7 on 2018-08-26 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catastro', '0002_auto_20151019_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleGeocoderCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('results', models.TextField()),
                ('ciudad', models.TextField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('hit', models.IntegerField(default=1)),
            ],
        ),
    ]
