# Generated by Django 2.0.7 on 2018-07-13 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catastro', '0002_auto_20151019_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudad',
            name='img_cuadrada',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='ciudad'),
        ),
        migrations.AlterField(
            model_name='ciudad',
            name='img_panorama',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='ciudad'),
        ),
        migrations.AlterField(
            model_name='imagenciudad',
            name='original',
            field=models.ImageField(upload_to='img/ciudades'),
        ),
    ]
