# Generated by Django 2.0.7 on 2018-08-27 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catastro', '0004_googlegeocodercache'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='googlegeocodercache',
            unique_together={('query', 'ciudad')},
        ),
    ]
