# Generated by Django 2.0.7 on 2018-07-29 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20151208_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linea',
            name='img_cuadrada',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='linea'),
        ),
        migrations.AlterField(
            model_name='linea',
            name='img_panorama',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='linea'),
        ),
        migrations.AlterField(
            model_name='recorrido',
            name='img_cuadrada',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='recorrido'),
        ),
        migrations.AlterField(
            model_name='recorrido',
            name='img_panorama',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='recorrido'),
        ),
    ]
