# Generated by Django 2.0.7 on 2018-07-13 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20151208_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='recorrido',
            name='osm_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recorrido',
            name='osm_sync',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='linea',
            name='img_cuadrada',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='linea'),
        ),
        migrations.AlterField(
            model_name='linea',
            name='img_panorama',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='linea'),
        ),
        migrations.AlterField(
            model_name='recorrido',
            name='img_cuadrada',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='recorrido'),
        ),
        migrations.AlterField(
            model_name='recorrido',
            name='img_panorama',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='recorrido'),
        ),
    ]
